name: Build Project 😎

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build project ✨
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform:
          - Android
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        # env:
        #   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        #   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        #   UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        id: buildProject
        # env:
        #   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        #   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        #   UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          allowDirtyBuild: true
          targetPlatform: ${{ matrix.targetPlatform }}
      #Get Version
      - name: Get Version
        uses: battila7/get-version-action@v2
        id: get_version
        run: echo ${{ steps.get_version.outputs.version }}
        run: echo ${{ steps.get_version.outputs.version-without-v }}

      #Return License
      - name: Return license
        uses: game-ci/unity-return-license@v2
        if: always()
      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}-${{ steps.buildProject.outputs.buildVersion }}
          path: build/${{ matrix.targetPlatform }}/${{ steps.buildProject.outputs.buildVersion }}
